steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: [
            'build',
            '-t',
            'us-central1-docker.pkg.dev/gcp-studies-436915/gcp-repo-test/zowyeapptest:${SHORT_SHA}',
            '-t',
            'us-central1-docker.pkg.dev/gcp-studies-436915/gcp-repo-test/zowyeapptest:latest',
            '--cache-from',
            'us-central1-docker.pkg.dev/gcp-studies-436915/gcp-repo-test/zowyeapptest:latest',
            '.'
          ]

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/gcp-studies-436915/gcp-repo-test/zowyeapptest:${SHORT_SHA}']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
            'run',
            'deploy',
            'my-cloud-run-service',
            '--image',
            'us-central1-docker.pkg.dev/gcp-studies-436915/gcp-repo-test/zowyeapptest:${SHORT_SHA}',
            '--platform',
            'managed',
            '--region',
            'us-central1',
            '--allow-unauthenticated',
            '--set-env-vars', 'someVar=zharah'
          ]

# Log Options
options:
  logging: CLOUD_LOGGING_ONLY

# Store images in Google Artifact Registry 
images:
  - us-central1-docker.pkg.dev/gcp-studies-436915/gcp-repo-test/zowyeapptest:${SHORT_SHA}
  - us-central1-docker.pkg.dev/gcp-studies-436915/gcp-repo-test/zowyeapptest:latest
